package com.github.starcats.blinkydome;

import heronarts.lx.model.LXModel;
import heronarts.lx.output.FadecandyOutput;
import heronarts.lx.output.LXOutput;
import heronarts.p3lx.P3LX;
import heronarts.p3lx.ui.UI3dContext;
import heronarts.p3lx.ui.component.UIPointCloud;
import heronarts.p3lx.ui.control.UIChannelControl;
import processing.core.PApplet;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppGui extends PApplet {

  private static boolean isVerbose = false;

  static public void main(String args[]) {
    PApplet.main(new String[] { "com.github.starcats.blinkydome.AppGui" });

    for (String s: args) {
      if (s.equalsIgnoreCase("-v")) {
        isVerbose = true;
      }
    }

    System.out.println(new AppGui().getGreeting());
  }

  public String getGreeting() {
      return "Hello world.";
  }

  private P3LX lx;

  private LXOutput fcOutput;

  private float lastDrawMs = 0;

  public void settings() {
    size(600, 600, P3D); //3D to force GPU blending
  }

  public void setup() {

    LXModel model = null;

//    AudioDetector.init(icosaFft.in.mix);

    lx = new P3LX(this, model);

    fcOutput = new FadecandyOutput(lx, "localhost", 7890);

    model.initLx(lx);

    model.addPatternsAndGo(lx, this, icosaFft);

    lx.addOutput(fcOutput);

    lx.ui.addLayer(
        new UI3dContext(lx.ui)
            .setCenter(model.cx, model.cy, model.cz)
            .setRadius(model.xMax - model.xMin)
            .addComponent(new UIPointCloud(lx, model).setPointSize(5))
    );

    lx.ui.addLayer(new UIChannelControl(lx.ui, lx, 16, 4, 4));

    Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {

      public void run () {

        System.out.println("Shutting down: turning all off...");

        fcOutput.mode.setValue(0d);
        fcOutput.send(null);
        for (int i=0; i<100000; i++)
          Thread.yield();
      }
    }
    ));
  }

  public void draw() {
    // Wipe the frame...
    background(0x292929);
    // ...and everything else is handled by P3LX!

//    icosaFft.forward();
//
//    AudioDetector.LINE_IN.tick(this.millis() - lastDrawMs, isVerbose);
    lastDrawMs = this.millis();
  }

}
